### PR TITLE
Implement Mozilla SOPS decryption

### PR DESCRIPTION
**Pull request by stefanprodan**
Decrypt [SOPS](https://github.com/mozilla/sops) encrypted manifests.

### CODE REVIEW

**Comment by marcbachmann** [comment]
Hi, just found this project. Was sops support removed again?

**Comment by stefanprodan** [comment]
Yeap, I wasn't happy with this experiment.

**Comment by marcbachmann** [comment]
looking forward for the flux extensions 😃 
still, something like that would be nice to have outside the flux ecosystem

**Comment by stefanprodan** [comment]
Flux has full support for SOPS. Given that kustomizer is a CLI same as SOPS, why wouldn't you run `sops decrypt` before `kustomizer apply`?

**Comment by marcbachmann** [comment]
> Flux has full support for SOPS.
was referencing the local diff support in works 😉 

> why wouldn't you run sops decrypt before kustomizer apply
To prevent secret decryption on disk.
Decrypt (and restoring) the file based on the file naming convention works 👍 
Just was looking for a simpler way than writing another wrapper script and prevent accidental diffs or commits of those secrets.

Anyways, I'm using flux and try to get customers using it. 😄 
Thanks for your work

**Pull request merged**
