### PR TITLE
Update Kustomize API and Go version

### PR DESCRIPTION
**Pull request by lalloni**
Uses the latest Kustomize version and updates Go version.

### CODE REVIEW

**Comment by stefanprodan** [comment]
@lalloni can you please rebase with upstream and force push

**Comment by stefanprodan** [comment]
@lalloni are you aware of https://github.com/fluxcd/flux2/issues/918 ?

**Comment by lalloni** [comment]
@stefanprodan I was partially aware (I'm using latest kustomize and needed to --enable_kyaml=false to avoid kyaml bugs, but wasn't hit by the go-getter issue).

In the case of kustomizer... what's the plan?

Somewhat related to this, I ended up using kustomizer as a post-processor replacing just kubectl-apply, after building the kustomization with kustomize proper, because otherwise it would break the build (because of #16), so it always receives a final plain k8s manifests yaml file, in which case this problem isn't significant.

**Comment by stefanprodan** [comment]
There is no  --enable_kyaml in latest kustomize

**Comment by lalloni** [comment]
Oh, I see... so I was confusing 3.9.x with 4.x...

**Comment by stefanprodan** [comment]
Closing this in favour of #17

**Pull request closed without merging**
