### PR TITLE
Support using custom command to run kubectl

### PR DESCRIPTION
**Pull request by lalloni**
Solves #13

### CODE REVIEW

**Comment by stefanprodan** [comment]
@lalloni can you please change this https://github.com/stefanprodan/kustomizer/blob/master/.github/workflows/e2e.yaml to:

- actions/setup-go@v2
- engineerd/setup-kind@v0.5.0

This should fix the CI. Thanks!

**Comment by lalloni** [comment]
@stefanprodan done

CI is still broken though...

**Comment by lalloni** [comment]
Fixed now!

**Review by stefanprodan — APPROVED** [review]
LGTM

Thanks @lalloni 🥇

**Pull request merged**
